name: run-xray-tests

on:
  workflow_dispatch:
    inputs:
      testPlanKey:
        description: 'Xray Test Plan'
        required: false

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run tests
        run: |
          echo "Running tests"

      - name: Upload results to Xray
        run: |
          curl -H "Content-Type: multipart/form-data" \
          -H "Authorization: Bearer $XRAY_CLIENT_TOKEN" \
          -X POST \
          -F "file=@results.xml" \
          "https://xray.cloud.getxray.app/api/v2/import/execution/junit?projectKey=YOURPROJECT"
